mode: predict

model:
  type: yolov5
  weights: object_detectors/models/yolo/weights/yolov5x.pt
  img_size: 640
  confidence_threshold: 0.25
  iou_threshold: 0.45
  device: cuda

dataset:
  used_dataset:   # coco | voc | openimages | null_image
    - coco
    # - null_image
  split:  # train | val | test
    - train
    # - val
  
  coco:
    root: D:/SEONGJIN/datasets/COCO
    train_split: train2017
    val_split: val2017
    test_split: test2017
    image_dir: images
    annotation_dir: annotations
    train_annotation_file: instances_train2017.json
    val_annotation_file: instances_val2017.json
    test_annotation_file: instances_test2017.json
  
  openimages:
    root: D:/SEONGJIN/datasets/OIDv4_ToolKit/OID/Dataset
    train_split: train
    val_split: validation
    test_split: test
    min_gt_boxes: 1  # keep only images with at least this many GT boxes

  null_image:
    num_samples: 20000
    # seed: 1234  # optional

dataloader:
  batch_size: 8
  num_workers: 4
  pin_memory: false
  shuffle_train: false
  shuffle_eval: false

output:
  uncertainty: layer_grad  # gt | score | full_softmax | entropy | energy | mc_dropout | ensemble | meta_detect | feature | feature_grad | layer_grad

  gt:
    unit: image  # image | bbox
    iou_match_threshold: 0.45
    save_csv:
      enabled: false
    
    save_image:
      enabled: true
      step: 10
      max_num: 10

  score:
    unit: image  # image | bbox
    pre_nms:
      enabled: false
      ratio: 1.0
    save_csv:
      enabled: false
      vector_reduction: [L1, L2, min, max, mean, std]

  full_softmax:
    unit: image  # image | bbox
    pre_nms:
      enabled: false
      ratio: 1.0
    save_csv:
      enabled: false
      vector_reduction: [L1, L2, min, max, mean, std]

  entropy:
    unit: image  # image | bbox
    pre_nms:
      enabled: false
      ratio: 1.0
    save_csv:
      enabled: false
      vector_reduction: [L1, L2, min, max, mean, std]

  energy:
    unit: image  # image | bbox
    pre_nms:
      enabled: false
      ratio: 1.0
    save_csv:
      enabled: false
      vector_reduction: [L1, L2, min, max, mean, std]

  mc_dropout:
    unit: image  # image | bbox
    num_runs: 30
    dropout_rate: 0.5
    queue_maxsize: 2
    save_csv:
      enabled: false
      vector_reduction: [L1, L2, min, max, mean, std]

  ensemble:
    unit: image  # image | bbox
    save_csv:
      enabled: false
      vector_reduction: [L1, L2, min, max, mean, std]

  meta_detect:
    unit: image  # image | bbox
    score_threshold: 0.0
    iou_threshold: 0.45
    save_csv:
      enabled: false
      vector_reduction: [L1, L2, min, max, mean, std]

  feature:
    unit: image  # image only
    layer: ["model.24.m.0", "model.24.m.1", "model.24.m.2"]
    save_csv:
      enabled: false
      reduction:
        map: none  # none | energy
        vector: [L1, L2, min, max, mean, std]

  feature_grad:
    unit: image  # image | bbox
    pre_nms:
      enabled: false
      ratio: 1.0
    gradient:
      scalar: [obj, cls]
      layer: ["model.24.m.0", "model.24.m.1", "model.24.m.2"]
    save_csv:
      enabled: false
      reduction:
        map: none
        vector: [L1, L2, min, max, mean, std]

  layer_grad:
    unit: image  # image | bbox
    pre_nms:
      enabled: false
      ratio: 0.0
    gradient:
      scalar: [loss]
      layer: disc_layers # all_conv | disc_layers | ["model.24.m.0", "model.24.m.1", "model.24.m.2"]
      target: null_target # cand_target | null_target
      ref_corrected: subtract # subtract | product | proj_removal | none
      ref_map: object_detectors/runs/references/04-22-2026_19;16_layer_grad_null_target_loss_noise
      use_norm: false
      disc_layers:
        fn_non_fn_map: object_detectors/runs/references/04-23-2026_00;40_layer_grad_null_target_loss_fn-non_fn
        separation_score: effect_size # effect_size | fisher_ratio
        topk: 3
    reference:
      gt: object_detectors/runs/fn_detectors/04-07-2026_14;09_gt
      group: [fn, non_fn]
      delta: 5.0e-4
      patience: 20
      min_samples: 200
      max_samples: 20000

    save_csv:
      data:
        enabled: true
        reduction:
          map: none
          vector: [L1, L2, min, max, mean, std]
      reference:
        progress:
          log: false # tensorboard event log
          raw_map: false
          norm_map: false
          step: 10
        final:
          raw_map: false
          norm_map: false # layer min-max normalization
    
    save_image:
      inferenced_image:
        enabled: false
        step: 10
        max_num: 10
      reference:
        progress:
          raw_map: false
          norm_map: false
          step: 10
        final:
          raw_map: false
          norm_map: false # layer min-max normalization
          profile: false
