mode: predict

model:
  type: yolov5
  weights: object_detectors/models/yolo/weights/bdd100k/yolov5x.pt
  img_size: 640
  confidence_threshold: 0.25
  iou_threshold: 0.45
  device: cuda

dataset:
  used_dataset:
    - bdd100k
  split:
    - val
  used_ratio:
    - 1.0

  bdd100k:
    root: D:/DataDrift/datasets/BDD100K
    train_split: train
    val_split: val
    train_image_dir: bdd100k/bdd100k/images/100k/train
    val_image_dir: bdd100k/bdd100k/images/100k/val
    train_annotation_file: bdd100k_labels_release/bdd100k/labels/bdd100k_labels_images_train.json
    val_annotation_file: bdd100k_labels_release/bdd100k/labels/bdd100k_labels_images_val.json

dataloader:
  batch_size: 8
  num_workers: 4
  pin_memory: false
  shuffle_train: false
  shuffle_eval: false

output:
  uncertainty: gt

  gt:
    iou_match_threshold: 0.45
    save_csv:
      enabled: true
    save_image:
      enabled: false
      step: 10
      max_num: 10

  predict_dump:
    iou_match_threshold: 0.45
    score_threshold: 0.0
    iou_threshold: 0.45
    save_csv:
      enabled: false

  score:
    save_csv:
      enabled: false

  class_probability:
    save_csv:
      enabled: false

  entropy:
    save_csv:
      enabled: false

  energy:
    save_csv:
      enabled: false

  mc_dropout:
    num_runs: 30
    dropout_rate: 0.5
    save_csv:
      enabled: false

  ensemble:
    weights: []
    save_csv:
      enabled: false

  meta_detect:
    score_threshold: 0.0
    iou_threshold: 0.45
    save_csv:
      enabled: false

  layer_grad:
    gradient:
      scalar: [loss]
      layer: ["model.24.m.0", "model.24.m.1", "model.24.m.2"]
      reduction: [l1_norm, l2_norm, min, max, mean, std]
      target: cand_target
      cand_score_threshold: 0.0
    save_csv:
      enabled: false
