mode: predict

model:
  type: yolov5
  weights: object_detectors/models/yolo/weights/yolov5x.pt
  img_size: 640
  confidence_threshold: 0.25
  iou_threshold: 0.45
  device: cuda

dataset:
  used_dataset:   # coco | voc | openimages | null_image
    - coco
    - null_image
  split:  # train | val | test
    - val
    - val
  
  coco:
    root: D:/SEONGJIN/datasets/COCO
    train_split: train2017
    val_split: val2017
    test_split: test2017
    image_dir: images
    annotation_dir: annotations
    train_annotation_file: instances_train2017.json
    val_annotation_file: instances_val2017.json
    test_annotation_file: instances_test2017.json
  
  openimages:
    root: D:/SEONGJIN/datasets/OIDv4_ToolKit/OID/Dataset
    train_split: train
    val_split: validation
    test_split: test
    min_gt_boxes: 1  # keep only images with at least this many GT boxes

  null_image:
    num_samples: 64
    # seed: 1234  # optional

dataloader:
  batch_size: 32
  num_workers: 4
  pin_memory: false
  shuffle_train: false
  shuffle_eval: false

output:
  uncertainty: layer_grad  # gt | score | full_softmax | entropy | energy | mc_dropout | ensemble | meta_detect | feature | feature_grad | layer_grad

  gt:
    save_csv:
      enabled: false
      unit: image  # image | bbox
      iou_match_threshold: 0.45
    save_image:
      enabled: true
      gt:
        step: 10
        max_num: 10

  score:
    save_csv:
      enabled: false
      unit: image  # image | bbox
      pre_nms:
        enabled: false
      vector_reduction: [L1, L2, min, max, mean, std]

  full_softmax:
    save_csv:
      enabled: false
      unit: image  # image | bbox
      pre_nms:
        enabled: false
      vector_reduction: [L1, L2, min, max, mean, std]

  entropy:
    save_csv:
      enabled: false
      unit: image  # image | bbox
      pre_nms:
        enabled: false
      vector_reduction: [L1, L2, min, max, mean, std]

  energy:
    save_csv:
      enabled: false
      unit: image  # image | bbox
      pre_nms:
        enabled: false
      vector_reduction: [L1, L2, min, max, mean, std]

  mc_dropout:
    save_csv:
      enabled: false
      unit: image  # image | bbox
      num_runs: 30
      dropout_rate: 0.5
      queue_maxsize: 2
      vector_reduction: [L1, L2, min, max, mean, std]

  ensemble:
    save_csv:
      enabled: false
      unit: image  # image | bbox
      vector_reduction: [L1, L2, min, max, mean, std]

  meta_detect:
    save_csv:
      enabled: false
      unit: image  # image | bbox
      score_threshold: 0.0
      iou_threshold: 0.45
      vector_reduction: [L1, L2, min, max, mean, std]

  feature:
    save_csv:
      enabled: false
      unit: image  # image only
      target_layer: ["model.24.m.0", "model.24.m.1", "model.24.m.2"]
      map_reduction: none  # none | energy
      vector_reduction: [L1, L2, min, max, mean, std]

  feature_grad:
    save_csv:
      enabled: false
      unit: image  # image | bbox
      pre_nms:
        enabled: false
      gradient:
        scalar: [obj, cls]
        layer: ["model.24.m.0", "model.24.m.1", "model.24.m.2"]
      reduction:
        map: none
        vector: [L1, L2, min, max, mean, std]

  layer_grad:
    save_csv:
      enabled: false
      unit: image  # image | bbox
      pre_nms:
        enabled: false
      gradient:
        scalar: [loss]
        layer: ["model.24.m.0", "model.24.m.1", "model.24.m.2"]
        target: null
      reduction:
        map: none
        vector: [L1, L2, min, max, mean, std]
    save_image:
      enabled: true
      layer_grad:
        mode: fix  # fix | convergence
        gt: object_detectors/runs/fn_detectors/04-07-2026_14;09_gt
        gradient:
          scalar: [loss]
          layer: ["model.24.m.0", "model.24.m.1", "model.24.m.2"]
          target: null
        normalize: layer_minmax  # layer_minmax | layer_trimmed_minmax | none
        save_mean_maps: true
        save_graph: true
        save_per_image: false
        csv:
          enabled: false
          save_running_log: true
          save_final_raw_map_csv: true
          save_final_norm_map_csv: true
        fix:
          num_fn: 20
          num_non_fn: 20
        convergence:
          delta_l2_tol: 1.0e-4
          patience: 20
          min_samples: 200
          max_samples: 20000
