mode: train

model:
  type: yolov5
  weights: object_detectors/models/yolo/weights/coco/yolov5x.pt
  img_size: 640
  confidence_threshold: 0.25
  iou_threshold: 0.45
  device: cuda

dataset:
  used_dataset: foggy_cityscapes
  used_ratio: 1.0

  foggy_cityscapes:
    root: D:/DataDrift/datasets/Cityscapes
    train_split: train
    val_split: val
    train_image_dir: leftImg8bit_foggy/train
    val_image_dir: leftImg8bit_foggy/val
    train_annotation_dir: gtFine/train
    val_annotation_dir: gtFine/val

dataloader:
  batch_size: 12
  num_workers: 4
  pin_memory: true
  shuffle_train: true
  shuffle_eval: false

loss:
  box: 0.05
  cls: 0.5
  obj: 1.0

training:
  epochs: 10
  lr: 0.0001
  weight_decay: 0.0001
  seed: 42
