mode: predict

model:
  type: yolov5
  weights: object_detectors/models/yolo/weights/yolov5x.pt
  img_size: 640
  confidence_threshold: 0.25
  iou_threshold: 0.45
  device: cuda

dataset:
  used_dataset: coco
  split: val
  
  coco:
    root: D:/DataDrift/datasets/COCO
    train_split: train2017
    val_split: val2017
    test_split: test2017
    image_dir: images
    annotation_dir: annotations
    train_annotation_file: instances_train2017.json
    val_annotation_file: instances_val2017.json
    test_annotation_file: instances_test2017.json

dataloader:
  batch_size: 1
  num_workers: 0
  pin_memory: false
  shuffle_train: false
  shuffle_eval: false

output:
  save_csv:
    enabled: true
    unit: image   # image | bbox
    uncertainty: feature_grad  # fn | tp | score | full_softmax | feature_grad | layer_grad
    
    fn: # per image
      iou_match_threshold: 0.45

    tp: # per bbox
      iou_match_threshold: 0.45

    score:
      enabled: true
      vector_reduction: [L1, L2, min, max, mean, std]  # only for unit: image

    full_softmax:
      enabled: true
    
    feature_grad:
      target_value: [obj, cls]  # loss | obj_loss | cls_loss | bbox_loss | obj | cls
      target_layer: ["model.24.m.0", "model.24.m.1", "model.24.m.2"]
      map_reduction: energy
      vector_reduction: [L1, L2, min, max, mean, std]  # empty list [] means save raw D vector

    layer_grad:
      target_value: [loss]  # loss | obj_loss | cls_loss | bbox_loss | obj | cls
      target_layer: ["model.24.m.0", "model.24.m.1", "model.24.m.2"]  # "model.17.cv3.conv", "model.20.cv3.conv", "model.23.cv3.conv"
      vector_reduction: [L1, L2, min, max, mean, std]  # empty list [] means save raw flattened gradients
  
  save_image:
    enabled: true
    step: 10
    max_num: 10
