mode: predict

model:
  type: yolov10
  weights: object_detectors/models/yolov10/weights/coco/yolov10n.pt
  img_size: 640
  variant: n
  max_det: 300
  confidence_threshold: 0.25
  device: cuda

dataset:
  used_dataset:   # coco | voc | openimages
    - coco
    # - coco
  split:  # train | val
    - train
    # - val
  used_ratio:
    - 0.1
    # - 1.0

  coco:
    root: D:/SEONGJIN/datasets/COCO
    train_split: train2017
    val_split: val2017
    image_dir: images
    annotation_dir: annotations
    train_annotation_file: instances_train2017.json
    val_annotation_file: instances_val2017.json

  voc:
    root: D:/SEONGJIN/datasets/VOC/VOCdevkit/VOC2012
    train_split: train
    val_split: val

  openimages:
    root: D:/SEONGJIN/datasets/OIDv4_ToolKit/OID/Dataset
    train_split: train
    val_split: validation
    test_split: test
    min_gt_boxes: 1

dataloader:
  batch_size: 4
  num_workers: 4
  pin_memory: false
  shuffle_train: false
  shuffle_eval: false

output:
  # gt | deterministic | score | class_probability | entropy | energy | mc_dropout | ensemble | null_detect | layer_grad
  uncertainty: score

  gt:
    iou_match_threshold: 0.45
    save_csv:
      enabled: true
    save_image:
      enabled: false
      step: 10
      max_num: 10

  score:
    save_csv:
      enabled: true

  class_probability:
    save_csv:
      enabled: true

  entropy:
    save_csv:
      enabled: true

  energy:
    save_csv:
      enabled: true

  mc_dropout:
    num_runs: 30
    dropout_rate: 0.5
    save_csv:
      enabled: true

  ensemble:
    weights: []
    save_csv:
      enabled: true

  null_detect:
    cls_loss: kl  # bcewithlogits | kl
    cls_direction: pred_to_target  # pred_to_target | target_to_pred, only for cls_loss: kl
    feature_set: full  # full | losses_only
    save_csv:
      enabled: true

  layer_grad:
    gradient:
      # null_target only:
      #   bbox_loss l1/l2: loss(final detection box source-point offset, zero offset)
      #   cls_loss: loss(source class logits, uniform/null class target)
      scalar: [bbox_loss, cls_loss]
      layer: ["model.23.one2one_cv2.0.2", "model.23.one2one_cv3.0.2"]
      reduction: [l1_norm, l2_norm, min, max, mean, std]
      target: null_target
      bbox_loss: l1  # l1 | l2
      cls_loss: bcewithlogits  # bcewithlogits | kl
      bbox_direction: pred_to_target
      cls_direction: pred_to_target
    save_csv:
      enabled: true
