mode: predict

model:
  type: faster_rcnn
  backbone: resnet50_fpn
  weights: object_detectors/models/faster_rcnn/weights/coco/fasterrcnn_resnet50_fpn_coco.pth
  pretrained: true
  confidence_threshold: 0.25
  iou_threshold: 0.45
  device: cuda

dataset:
  used_dataset:
    - bdd100k
  split:
    - val
  used_ratio:
    - 1.0
  bdd100k:
    root: D:/SEONGJIN/datasets/BDD100K
    train_split: train
    val_split: val
    train_image_dir: bdd100k/bdd100k/images/100k/train
    val_image_dir: bdd100k/bdd100k/images/100k/val
    train_annotation_file: bdd100k_labels_release/bdd100k/labels/bdd100k_labels_images_train.json
    val_annotation_file: bdd100k_labels_release/bdd100k/labels/bdd100k_labels_images_val.json

dataloader:
  batch_size: 4
  num_workers: 4
  pin_memory: false
  shuffle_train: false
  shuffle_eval: false
  aspect_ratio_grouping: true

output:
  uncertainty: gt  # gt | deterministic | score | class_probability | entropy | energy | mc_dropout | ensemble | meta_detect | layer_grad
  gt:
    iou_match_threshold: 0.45
    save_csv: {enabled: true}
    save_image: {enabled: false, step: 10, max_num: 10}
  score: {save_csv: {enabled: false}}
  class_probability: {save_csv: {enabled: false}}
  entropy: {save_csv: {enabled: false}}
  energy: {save_csv: {enabled: false}}
  mc_dropout:
    num_runs: 30
    dropout_rate: 0.5
    save_csv: {enabled: false}
  ensemble:
    weights: []
    save_csv: {enabled: false}
  meta_detect:
    score_threshold: 0.0
    iou_threshold: 0.45
    save_csv: {enabled: false}
  layer_grad:
    gradient:
      target: cand_target
      reduction: [l1_norm, l2_norm, min, max, mean, std]
      cand_target:
        rpn_cand:
          enabled: true
          scalar: [obj_loss, bbox_loss]
          layer:
            obj_loss: ["rpn.head.conv", "rpn.head.cls_logits"]
            bbox_loss: ["rpn.head.conv", "rpn.head.bbox_pred"]
          cand_obj_threshold: 0.0
          obj_loss: bcewithlogits
          bbox_loss: l1  # l1 | l2
          obj_direction: pred_to_target
          bbox_direction: pred_to_target
        roi_cand:
          enabled: true
          scalar: [cls_loss, bbox_loss]
          layer:
            cls_loss: ["roi_heads.box_head.fc7", "roi_heads.box_predictor.cls_score"]
            bbox_loss: ["roi_heads.box_head.fc7", "roi_heads.box_predictor.bbox_pred"]
          cand_score_threshold: 0.0
          cls_loss: bcewithlogits  # bcewithlogits | kl | ce
          bbox_loss: l1  # l1 | l2
          cls_direction: pred_to_target
          bbox_direction: pred_to_target
      null_target:
        rpn:
          enabled: true
          scalar: [obj_loss, bbox_loss]
          layer:
            obj_loss: ["rpn.head.conv", "rpn.head.cls_logits"]
            bbox_loss: ["rpn.head.conv", "rpn.head.bbox_pred"]
          obj_loss: bcewithlogits  # bcewithlogits | abs_diff | diff
          bbox_loss: l1  # l1 | l2
          obj_target: 0.5
          obj_direction: pred_to_target
          bbox_direction: pred_to_target
        roi:
          enabled: true
          scalar: [cls_loss, bbox_loss]
          layer:
            cls_loss: ["roi_heads.box_head.fc7", "roi_heads.box_predictor.cls_score"]
            bbox_loss: ["roi_heads.box_head.fc7", "roi_heads.box_predictor.bbox_pred"]
          cls_loss: bcewithlogits  # bcewithlogits | kl | ce
          bbox_loss: l1  # l1 | l2
          cls_direction: pred_to_target
          bbox_direction: pred_to_target
    save_csv: {enabled: false}

