mode: train

model:
  type: gb_classifier         # logistic | gb_classifier
  device: cpu                 # cpu | cuda
  search: false
  search_scoring: roc_auc

dataset:
  # object_detectors/runs/{time}
  root: object_detectors/runs/03-13-2026_18;00

train:
  augmentation: none           # none | smote
  test_size: 0.3
  repeats: 15
  n_jobs: 8
  random_seed: 42
