return {
 ["name:Arial/B:mode=node;script=latn;language=dflt;#b#655361"]={ "c:/Windows/Fonts/arialbd.ttf", false },
 ["name:Arial/B:mode=node;script=latn;language=dflt;#b#655362"]={ "c:/Windows/Fonts/arialbd.ttf", false },
 ["name:Arial/B:mode=node;script=latn;language=dflt;+tlig;#b#524288"]={ "c:/Windows/Fonts/arialbd.ttf", false },
 ["name:Arial/B:mode=node;script=latn;language=dflt;+tlig;#b#589824"]={ "c:/Windows/Fonts/arialbd.ttf", false },
 ["name:Arial/BI:mode=node;script=latn;language=dflt;#bi#655361"]={ "c:/Windows/Fonts/ARIALNBI.TTF", false },
 ["name:Arial/BI:mode=node;script=latn;language=dflt;#bi#655362"]={ "c:/Windows/Fonts/ARIALNBI.TTF", false },
 ["name:Arial/I:mode=node;script=latn;language=dflt;#i#655361"]={ "c:/Windows/Fonts/ARIALNI.TTF", false },
 ["name:Arial/I:mode=node;script=latn;language=dflt;#i#655362"]={ "c:/Windows/Fonts/ARIALNI.TTF", false },
 ["name:Arial:mode=node;#655358"]={ "c:/Windows/Fonts/arial.ttf", false },
 ["name:Arial:mode=node;#655362"]={ "c:/Windows/Fonts/arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;#655361"]={ "c:/Windows/Fonts/arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;#655362"]={ "c:/Windows/Fonts/arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#327680"]={ "c:/Windows/Fonts/arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#340787"]={ "c:/Windows/Fonts/arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#380109"]={ "c:/Windows/Fonts/arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#393216"]={ "c:/Windows/Fonts/arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#406323"]={ "c:/Windows/Fonts/arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#458752"]={ "c:/Windows/Fonts/arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#524288"]={ "c:/Windows/Fonts/arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#589824"]={ "c:/Windows/Fonts/arial.ttf", false },
 ["name:Arial:mode=node;script=latn;language=dflt;+tlig;#655360"]={ "c:/Windows/Fonts/arial.ttf", false },
}