mode: train

model:
  type: gb_classifier         # logistic | gb_classifier
  device: cpu                 # cpu | cuda
  random_seed: 42
  search: false
  search_scoring: roc_auc

dataset:
  input_root:
    - object_detectors/runs/fn_detectors/03-12-2026_18;34_feature_grad
    # - object_detectors/runs/fn_detectors/03-12-2026_18;34_entropy
  gt_root: object_detectors/runs/fn_detectors/04-07-2026_14;09_gt

experiment:
  process: repeat              # kfold | repeat
  augmentation: none           # none | smote
  n_jobs: 8

  kfold:
    num_fold: 10

  repeat:
    split: 0.3
    repeats: 15
